In [1]:
import json
import os
from PIL import Image
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm import tqdm

In [2]:
# Define the image transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

In [3]:
class ImageDataset(Dataset):
    def __init__(self, image_dir, info_file, transform=None):
        self.image_dir = image_dir
        self.image_paths = []
        self.labels = []
        self.label_to_idx = {}
        
        with open(info_file, 'r') as f:
            info = json.load(f)
        
        # Create a mapping from labels to integers
        unique_labels = set(info.values())
        for idx, label in enumerate(unique_labels):
            self.label_to_idx[label] = idx
        
        for image_path, label in info.items():
            self.image_paths.append(os.path.join(image_dir, image_path))
            self.labels.append(self.label_to_idx[label])  # Convert label to integer using the mapping
        
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)
    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        try:
            image = Image.open(image_path).convert('RGB')
        except FileNotFoundError:
            print(f"Error: File not found: {image_path}")
            # Return a default value or handle the missing file appropriately
            return torch.zeros(3, 224, 224), 0  # Replace with your desired default value

        if self.transform:
            image = self.transform(image)
        label = self.labels[idx]
        # image = image.unsqueeze(0)  # Add a batch dimension
        return image, label

#     def __getitem__(self, idx):
#         image_path = self.image_paths[idx]
#         image = Image.open(image_path).convert('RGB')
#         if self.transform:
#             image = self.transform(image)
#         label = self.labels[idx]
#         # image = image.unsqueeze(0)  # Add a batch dimension
#         return image, label


In [4]:
# Define the contrastive loss function
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, x1, x2, y):
        distances = torch.sqrt(((x1 - x2) ** 2).sum(dim=1))
        losses = y * distances ** 2 + (1 - y) * torch.clamp(self.margin - distances, min=0.0) ** 2
        return losses.mean()

In [5]:
# Define the image similarity model
class ImageSimilarityModel(nn.Module):
    def __init__(self):
        super(ImageSimilarityModel, self).__init__()
        self.backbone = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(128, 256, kernel_size=3, stride=2, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(256, 512, kernel_size=3, stride=2, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.fc = nn.Linear(512 * 1 * 1, 128)
    def forward(self, x):
        x = self.backbone(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

In [6]:


# Load the dataset
train_dataset = ImageDataset('train/', 'train_image_info.json', transform=transform)
query_dataset = ImageDataset('query_images/', 'test_image_info.json', transform=transform)
gallery_dataset = ImageDataset('gallery/', 'test_image_info.json', transform=transform)

In [7]:
train_dataset

In [8]:

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
query_loader = DataLoader(query_dataset, batch_size=1, shuffle=False)
gallery_loader = DataLoader(gallery_dataset, batch_size=1, shuffle=False)

In [9]:
# Initialize the model and optimizer
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = ImageSimilarityModel().to(device)
criterion = ContrastiveLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [10]:
num_epochs = 30
for epoch in range(num_epochs):
    running_loss = 0.0
    for images, labels in tqdm(train_loader, desc=f'Epoch {epoch+1}/{num_epochs}'):
        images = images.to(device)
        labels = [label.to(device) for label in labels]

        optimizer.zero_grad()
        embeddings = model(images)

        # Create matching and non-matching pairs
        batch_size = embeddings.size(0)
        y = torch.eye(batch_size).to(device)  # Create a batch-wise identity matrix
        y = y.view(-1)  # Flatten the matrix to create matching/non-matching pairs

        anchor_embeddings = embeddings.repeat(batch_size, 1)  # Repeat anchor embeddings
        positive_embeddings = embeddings.repeat(1, batch_size).view(-1, embeddings.size(-1))  # Repeat positive embeddings

        loss = criterion(anchor_embeddings, positive_embeddings, y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    print(f'Epoch {epoch+1}/{num_epochs}, Loss: {running_loss / len(train_loader)}')

Epoch 1/30: 100%|█████████████████████████████| 358/358 [03:34<00:00,  1.67it/s]


Epoch 1/30, Loss: nan


Epoch 2/30: 100%|█████████████████████████████| 358/358 [04:07<00:00,  1.45it/s]


Epoch 2/30, Loss: nan


Epoch 3/30: 100%|█████████████████████████████| 358/358 [04:43<00:00,  1.26it/s]


Epoch 3/30, Loss: nan


Epoch 4/30: 100%|█████████████████████████████| 358/358 [04:25<00:00,  1.35it/s]


Epoch 4/30, Loss: nan


Epoch 5/30: 100%|█████████████████████████████| 358/358 [03:32<00:00,  1.68it/s]


Epoch 5/30, Loss: nan


Epoch 6/30: 100%|█████████████████████████████| 358/358 [03:31<00:00,  1.69it/s]


Epoch 6/30, Loss: nan


Epoch 7/30: 100%|█████████████████████████████| 358/358 [03:29<00:00,  1.71it/s]


Epoch 7/30, Loss: nan


Epoch 8/30: 100%|█████████████████████████████| 358/358 [03:28<00:00,  1.72it/s]


Epoch 8/30, Loss: nan


Epoch 9/30: 100%|█████████████████████████████| 358/358 [03:29<00:00,  1.71it/s]


Epoch 9/30, Loss: nan


Epoch 10/30: 100%|████████████████████████████| 358/358 [03:33<00:00,  1.68it/s]


Epoch 10/30, Loss: nan


Epoch 11/30: 100%|████████████████████████████| 358/358 [04:04<00:00,  1.46it/s]


Epoch 11/30, Loss: nan


Epoch 12/30: 100%|████████████████████████████| 358/358 [04:05<00:00,  1.46it/s]


Epoch 12/30, Loss: nan


Epoch 13/30: 100%|████████████████████████████| 358/358 [04:16<00:00,  1.39it/s]


Epoch 13/30, Loss: nan


Epoch 14/30: 100%|████████████████████████████| 358/358 [04:07<00:00,  1.45it/s]


Epoch 14/30, Loss: nan


Epoch 15/30: 100%|████████████████████████████| 358/358 [04:04<00:00,  1.46it/s]


Epoch 15/30, Loss: nan


Epoch 16/30: 100%|████████████████████████████| 358/358 [04:04<00:00,  1.47it/s]


Epoch 16/30, Loss: nan


Epoch 17/30: 100%|████████████████████████████| 358/358 [04:09<00:00,  1.44it/s]


Epoch 17/30, Loss: nan


Epoch 18/30: 100%|████████████████████████████| 358/358 [04:07<00:00,  1.45it/s]


Epoch 18/30, Loss: nan


Epoch 19/30: 100%|████████████████████████████| 358/358 [04:07<00:00,  1.44it/s]


Epoch 19/30, Loss: nan


Epoch 20/30: 100%|████████████████████████████| 358/358 [04:06<00:00,  1.45it/s]


Epoch 20/30, Loss: nan


Epoch 21/30: 100%|████████████████████████████| 358/358 [04:08<00:00,  1.44it/s]


Epoch 21/30, Loss: nan


Epoch 22/30: 100%|████████████████████████████| 358/358 [04:07<00:00,  1.44it/s]


Epoch 22/30, Loss: nan


Epoch 23/30: 100%|████████████████████████████| 358/358 [04:09<00:00,  1.44it/s]


Epoch 23/30, Loss: nan


Epoch 24/30: 100%|████████████████████████████| 358/358 [04:12<00:00,  1.42it/s]


Epoch 24/30, Loss: nan


Epoch 25/30: 100%|████████████████████████████| 358/358 [04:06<00:00,  1.45it/s]


Epoch 25/30, Loss: nan


Epoch 26/30: 100%|████████████████████████████| 358/358 [04:06<00:00,  1.45it/s]


Epoch 26/30, Loss: nan


Epoch 27/30: 100%|████████████████████████████| 358/358 [04:10<00:00,  1.43it/s]


Epoch 27/30, Loss: nan


Epoch 28/30: 100%|████████████████████████████| 358/358 [04:06<00:00,  1.45it/s]


Epoch 28/30, Loss: nan


Epoch 29/30: 100%|████████████████████████████| 358/358 [04:09<00:00,  1.43it/s]


Epoch 29/30, Loss: nan


Epoch 30/30: 100%|████████████████████████████| 358/358 [04:06<00:00,  1.45it/s]

Epoch 30/30, Loss: nan


In [11]:
query_embeddings = []
gallery_embeddings = []

with torch.no_grad():
    for query_image, _ in tqdm(query_loader, desc='Computing query embeddings'):
        query_image = query_image.to(device)
        embedding = model(query_image)
        query_embeddings.append(embedding)

    for gallery_image, _ in tqdm(gallery_loader, desc='Computing gallery embeddings'):
        gallery_image = gallery_image.to(device)
        embedding = model(gallery_image)
        gallery_embeddings.append(embedding)

query_embeddings = torch.cat(query_embeddings, dim=0)
gallery_embeddings = torch.cat(gallery_embeddings, dim=0)

Computing query embeddings:   1%|▏           | 13/1150 [00:00<00:08, 126.45it/s]

Error: File not found: query_images/Image_10506.jpg
Error: File not found: query_images/Image_4904.jpg
Error: File not found: query_images/Image_4080.jpg
Error: File not found: query_images/Image_9516.jpg
Error: File not found: query_images/Image_2124.jpg
Error: File not found: query_images/Image_5555.jpg
Error: File not found: query_images/Image_11382.jpg
Error: File not found: query_images/Image_10259.jpg
Error: File not found: query_images/Image_3842.jpg
Error: File not found: query_images/Image_5510.jpg
Error: File not found: query_images/Image_9721.jpg
Error: File not found: query_images/Image_9186.jpg
Error: File not found: query_images/Image_5552.jpg
Error: File not found: query_images/Image_5657.jpg
Error: File not found: query_images/Image_3789.jpg
Error: File not found: query_images/Image_3178.jpg
Error: File not found: query_images/Image_5829.jpg
Error: File not found: query_images/Image_5570.jpg
Error: File not found: query_images/Image_9366.jpg
Error: File not found: query

Computing query embeddings:   2%|▎           | 28/1150 [00:00<00:08, 139.81it/s]

Error: File not found: query_images/Image_8684.jpg
Error: File not found: query_images/Image_10406.jpg
Error: File not found: query_images/Image_1364.jpg
Error: File not found: query_images/Image_11077.jpg
Error: File not found: query_images/Image_3779.jpg
Error: File not found: query_images/Image_7523.jpg
Error: File not found: query_images/Image_10020.jpg


Computing query embeddings:   4%|▍           | 43/1150 [00:00<00:07, 139.58it/s]

Error: File not found: query_images/Image_2285.jpg
Error: File not found: query_images/Image_542.jpg
Error: File not found: query_images/Image_1788.jpg
Error: File not found: query_images/Image_3738.jpg
Error: File not found: query_images/Image_3370.jpg
Error: File not found: query_images/Image_10201.jpg
Error: File not found: query_images/Image_6171.jpg
Error: File not found: query_images/Image_2828.jpg
Error: File not found: query_images/Image_8121.jpg
Error: File not found: query_images/Image_4024.jpg
Error: File not found: query_images/Image_11332.jpg
Error: File not found: query_images/Image_3883.jpg
Error: File not found: query_images/Image_8732.jpg
Error: File not found: query_images/Image_6721.jpg
Error: File not found: query_images/Image_7647.jpg
Error: File not found: query_images/Image_3865.jpg
Error: File not found: query_images/Image_3580.jpg
Error: File not found: query_images/Image_10453.jpg
Error: File not found: query_images/Image_8942.jpg
Error: File not found: query_

Computing query embeddings:   5%|▌           | 58/1150 [00:00<00:07, 138.64it/s]

Error: File not found: query_images/Image_33.jpg
Error: File not found: query_images/Image_4443.jpg
Error: File not found: query_images/Image_242.jpg
Error: File not found: query_images/Image_5442.jpg
Error: File not found: query_images/Image_589.jpg


Computing query embeddings:   7%|▊           | 77/1150 [00:00<00:06, 154.54it/s]

Error: File not found: query_images/Image_7315.jpg
Error: File not found: query_images/Image_2693.jpg
Error: File not found: query_images/Image_2491.jpg
Error: File not found: query_images/Image_5801.jpg
Error: File not found: query_images/Image_8139.jpg
Error: File not found: query_images/Image_2417.jpg
Error: File not found: query_images/Image_1435.jpg
Error: File not found: query_images/Image_4543.jpg
Error: File not found: query_images/Image_1320.jpg
Error: File not found: query_images/Image_12126.jpg
Error: File not found: query_images/Image_8209.jpg
Error: File not found: query_images/Image_519.jpg
Error: File not found: query_images/Image_640.jpg
Error: File not found: query_images/Image_4333.jpg
Error: File not found: query_images/Image_1347.jpg
Error: File not found: query_images/Image_643.jpg
Error: File not found: query_images/Image_11076.jpg
Error: File not found: query_images/Image_472.jpg
Error: File not found: query_images/Image_8661.jpg
Error: File not found: query_imag

Computing query embeddings:   8%|▉           | 94/1150 [00:00<00:06, 157.89it/s]

Error: File not found: query_images/Image_7233.jpg
Error: File not found: query_images/Image_10572.jpg
Error: File not found: query_images/Image_1024.jpg
Error: File not found: query_images/Image_5395.jpg
Error: File not found: query_images/Image_8308.jpg
Error: File not found: query_images/Image_458.jpg
Error: File not found: query_images/Image_10960.jpg
Error: File not found: query_images/Image_8866.jpg


Computing query embeddings:  10%|█          | 110/1150 [00:00<00:06, 158.06it/s]

Error: File not found: query_images/Image_8027.jpg
Error: File not found: query_images/Image_8329.jpg
Error: File not found: query_images/Image_1374.jpg
Error: File not found: query_images/Image_11898.jpg
Error: File not found: query_images/Image_8632.jpg
Error: File not found: query_images/Image_3171.jpg
Error: File not found: query_images/Image_2.jpg
Error: File not found: query_images/Image_6135.jpg
Error: File not found: query_images/Image_9162.jpg
Error: File not found: query_images/Image_6674.jpg
Error: File not found: query_images/Image_11468.jpg
Error: File not found: query_images/Image_4574.jpg
Error: File not found: query_images/Image_6729.jpg
Error: File not found: query_images/Image_9888.jpg
Error: File not found: query_images/Image_3335.jpg
Error: File not found: query_images/Image_3972.jpg
Error: File not found: query_images/Image_6030.jpg
Error: File not found: query_images/Image_7833.jpg
Error: File not found: query_images/Image_3818.jpg
Error: File not found: query_ima

Computing query embeddings:  11%|█▏         | 129/1150 [00:00<00:06, 167.59it/s]

Error: File not found: query_images/Image_5962.jpg
Error: File not found: query_images/Image_11800.jpg
Error: File not found: query_images/Image_7581.jpg
Error: File not found: query_images/Image_8033.jpg
Error: File not found: query_images/Image_8134.jpg
Error: File not found: query_images/Image_11215.jpg
Error: File not found: query_images/Image_4974.jpg
Error: File not found: query_images/Image_12254.jpg
Error: File not found: query_images/Image_8689.jpg


Computing query embeddings:  13%|█▍         | 146/1150 [00:00<00:06, 159.74it/s]

Error: File not found: query_images/Image_2190.jpg
Error: File not found: query_images/Image_6891.jpg
Error: File not found: query_images/Image_3026.jpg
Error: File not found: query_images/Image_4690.jpg
Error: File not found: query_images/Image_11013.jpg
Error: File not found: query_images/Image_3708.jpg
Error: File not found: query_images/Image_3369.jpg
Error: File not found: query_images/Image_11627.jpg
Error: File not found: query_images/Image_1820.jpg
Error: File not found: query_images/Image_115.jpg
Error: File not found: query_images/Image_10957.jpg
Error: File not found: query_images/Image_10897.jpg
Error: File not found: query_images/Image_4755.jpg
Error: File not found: query_images/Image_8043.jpg
Error: File not found: query_images/Image_5371.jpg
Error: File not found: query_images/Image_11393.jpg
Error: File not found: query_images/Image_7935.jpg
Error: File not found: query_images/Image_2474.jpg
Error: File not found: query_images/Image_4169.jpg
Error: File not found: quer

Computing query embeddings:  16%|█▋         | 180/1150 [00:01<00:06, 156.38it/s]

Error: File not found: query_images/Image_7649.jpg
Error: File not found: query_images/Image_4757.jpg
Error: File not found: query_images/Image_11831.jpg
Error: File not found: query_images/Image_10200.jpg
Error: File not found: query_images/Image_204.jpg
Error: File not found: query_images/Image_1677.jpg
Error: File not found: query_images/Image_7972.jpg
Error: File not found: query_images/Image_11282.jpg
Error: File not found: query_images/Image_6753.jpg
Error: File not found: query_images/Image_1437.jpg
Error: File not found: query_images/Image_11105.jpg
Error: File not found: query_images/Image_2621.jpg
Error: File not found: query_images/Image_3558.jpg
Error: File not found: query_images/Image_514.jpg
Error: File not found: query_images/Image_7546.jpg
Error: File not found: query_images/Image_7798.jpg
Error: File not found: query_images/Image_8612.jpg
Error: File not found: query_images/Image_9145.jpg
Error: File not found: query_images/Image_11848.jpg
Error: File not found: query

Computing query embeddings:  19%|██         | 215/1150 [00:01<00:05, 162.88it/s]

Error: File not found: query_images/Image_3853.jpg
Error: File not found: query_images/Image_3196.jpg
Error: File not found: query_images/Image_8025.jpg
Error: File not found: query_images/Image_3435.jpg
Error: File not found: query_images/Image_5634.jpg
Error: File not found: query_images/Image_6471.jpg
Error: File not found: query_images/Image_1991.jpg
Error: File not found: query_images/Image_5019.jpg
Error: File not found: query_images/Image_8303.jpg
Error: File not found: query_images/Image_10593.jpg
Error: File not found: query_images/Image_5018.jpg
Error: File not found: query_images/Image_1186.jpg
Error: File not found: query_images/Image_5616.jpg
Error: File not found: query_images/Image_7859.jpg
Error: File not found: query_images/Image_11625.jpg
Error: File not found: query_images/Image_3859.jpg
Error: File not found: query_images/Image_2081.jpg
Error: File not found: query_images/Image_7073.jpg
Error: File not found: query_images/Image_6949.jpg
Error: File not found: query_

Computing query embeddings:  22%|██▍        | 256/1150 [00:01<00:04, 182.45it/s]

Error: File not found: query_images/Image_4338.jpg
Error: File not found: query_images/Image_7660.jpg
Error: File not found: query_images/Image_8642.jpg
Error: File not found: query_images/Image_6644.jpg
Error: File not found: query_images/Image_9897.jpg
Error: File not found: query_images/Image_3890.jpg
Error: File not found: query_images/Image_5453.jpg
Error: File not found: query_images/Image_1228.jpg
Error: File not found: query_images/Image_10617.jpg
Error: File not found: query_images/Image_9875.jpg
Error: File not found: query_images/Image_6692.jpg
Error: File not found: query_images/Image_3065.jpg
Error: File not found: query_images/Image_786.jpg
Error: File not found: query_images/Image_8758.jpg
Error: File not found: query_images/Image_6354.jpg
Error: File not found: query_images/Image_963.jpg
Error: File not found: query_images/Image_9975.jpg
Error: File not found: query_images/Image_569.jpg
Error: File not found: query_images/Image_714.jpg
Error: File not found: query_image

Computing query embeddings:  26%|██▊        | 297/1150 [00:01<00:04, 191.22it/s]

Error: File not found: query_images/Image_6436.jpg
Error: File not found: query_images/Image_926.jpg
Error: File not found: query_images/Image_3845.jpg
Error: File not found: query_images/Image_5605.jpg
Error: File not found: query_images/Image_4814.jpg
Error: File not found: query_images/Image_2943.jpg
Error: File not found: query_images/Image_8169.jpg
Error: File not found: query_images/Image_2384.jpg
Error: File not found: query_images/Image_8685.jpg
Error: File not found: query_images/Image_479.jpg
Error: File not found: query_images/Image_8095.jpg
Error: File not found: query_images/Image_6889.jpg
Error: File not found: query_images/Image_862.jpg
Error: File not found: query_images/Image_9789.jpg
Error: File not found: query_images/Image_5514.jpg
Error: File not found: query_images/Image_6212.jpg
Error: File not found: query_images/Image_3333.jpg
Error: File not found: query_images/Image_1662.jpg
Error: File not found: query_images/Image_1289.jpg
Error: File not found: query_image

Computing query embeddings:  30%|███▎       | 340/1150 [00:01<00:04, 200.65it/s]

Error: File not found: query_images/Image_98.jpg
Error: File not found: query_images/Image_9891.jpg
Error: File not found: query_images/Image_6236.jpg
Error: File not found: query_images/Image_7512.jpg
Error: File not found: query_images/Image_4484.jpg
Error: File not found: query_images/Image_4527.jpg
Error: File not found: query_images/Image_10931.jpg
Error: File not found: query_images/Image_9076.jpg
Error: File not found: query_images/Image_6824.jpg
Error: File not found: query_images/Image_8701.jpg
Error: File not found: query_images/Image_1678.jpg
Error: File not found: query_images/Image_8060.jpg
Error: File not found: query_images/Image_4145.jpg
Error: File not found: query_images/Image_1957.jpg
Error: File not found: query_images/Image_3585.jpg
Error: File not found: query_images/Image_8012.jpg
Error: File not found: query_images/Image_3918.jpg
Error: File not found: query_images/Image_11703.jpg
Error: File not found: query_images/Image_1755.jpg
Error: File not found: query_im

Computing query embeddings:  33%|███▋       | 383/1150 [00:02<00:03, 204.23it/s]

Error: File not found: query_images/Image_12522.jpg
Error: File not found: query_images/Image_1899.jpg
Error: File not found: query_images/Image_11091.jpg
Error: File not found: query_images/Image_1177.jpg
Error: File not found: query_images/Image_1349.jpg
Error: File not found: query_images/Image_6085.jpg
Error: File not found: query_images/Image_12488.jpg
Error: File not found: query_images/Image_9815.jpg
Error: File not found: query_images/Image_811.jpg
Error: File not found: query_images/Image_7491.jpg
Error: File not found: query_images/Image_12406.jpg
Error: File not found: query_images/Image_4136.jpg
Error: File not found: query_images/Image_1173.jpg
Error: File not found: query_images/Image_1661.jpg
Error: File not found: query_images/Image_868.jpg
Error: File not found: query_images/Image_9821.jpg
Error: File not found: query_images/Image_10396.jpg
Error: File not found: query_images/Image_1995.jpg
Error: File not found: query_images/Image_3208.jpg
Error: File not found: query

Computing query embeddings:  37%|████       | 426/1150 [00:02<00:03, 205.56it/s]

Error: File not found: query_images/Image_5773.jpg
Error: File not found: query_images/Image_10807.jpg
Error: File not found: query_images/Image_5335.jpg
Error: File not found: query_images/Image_9740.jpg
Error: File not found: query_images/Image_4389.jpg
Error: File not found: query_images/Image_11745.jpg
Error: File not found: query_images/Image_11031.jpg
Error: File not found: query_images/Image_1270.jpg
Error: File not found: query_images/Image_2258.jpg
Error: File not found: query_images/Image_5108.jpg
Error: File not found: query_images/Image_1803.jpg
Error: File not found: query_images/Image_8054.jpg
Error: File not found: query_images/Image_3216.jpg
Error: File not found: query_images/Image_7949.jpg
Error: File not found: query_images/Image_9777.jpg
Error: File not found: query_images/Image_5184.jpg
Error: File not found: query_images/Image_785.jpg
Error: File not found: query_images/Image_1710.jpg
Error: File not found: query_images/Image_912.jpg
Error: File not found: query_i

Computing query embeddings:  41%|████▍      | 469/1150 [00:02<00:03, 205.08it/s]

Error: File not found: query_images/Image_10680.jpg
Error: File not found: query_images/Image_6310.jpg
Error: File not found: query_images/Image_691.jpg
Error: File not found: query_images/Image_7648.jpg
Error: File not found: query_images/Image_11713.jpg
Error: File not found: query_images/Image_6850.jpg
Error: File not found: query_images/Image_11112.jpg
Error: File not found: query_images/Image_6042.jpg
Error: File not found: query_images/Image_9148.jpg
Error: File not found: query_images/Image_8200.jpg
Error: File not found: query_images/Image_3022.jpg
Error: File not found: query_images/Image_7317.jpg
Error: File not found: query_images/Image_8911.jpg
Error: File not found: query_images/Image_8343.jpg
Error: File not found: query_images/Image_5300.jpg
Error: File not found: query_images/Image_8061.jpg
Error: File not found: query_images/Image_7929.jpg
Error: File not found: query_images/Image_1071.jpg
Error: File not found: query_images/Image_6429.jpg
Error: File not found: query_

Computing query embeddings:  44%|████▉      | 511/1150 [00:02<00:03, 205.18it/s]

Error: File not found: query_images/Image_12360.jpg
Error: File not found: query_images/Image_970.jpg
Error: File not found: query_images/Image_8881.jpg
Error: File not found: query_images/Image_10804.jpg
Error: File not found: query_images/Image_3711.jpg
Error: File not found: query_images/Image_753.jpg
Error: File not found: query_images/Image_11756.jpg
Error: File not found: query_images/Image_509.jpg
Error: File not found: query_images/Image_7685.jpg
Error: File not found: query_images/Image_8594.jpg
Error: File not found: query_images/Image_7262.jpg
Error: File not found: query_images/Image_3812.jpg
Error: File not found: query_images/Image_6291.jpg
Error: File not found: query_images/Image_9601.jpg
Error: File not found: query_images/Image_737.jpg
Error: File not found: query_images/Image_10618.jpg
Error: File not found: query_images/Image_8987.jpg
Error: File not found: query_images/Image_8215.jpg
Error: File not found: query_images/Image_12157.jpg
Error: File not found: query_i

Computing query embeddings:  48%|█████▎     | 553/1150 [00:03<00:02, 207.35it/s]

Error: File not found: query_images/Image_6043.jpg
Error: File not found: query_images/Image_1945.jpg
Error: File not found: query_images/Image_3923.jpg
Error: File not found: query_images/Image_7971.jpg
Error: File not found: query_images/Image_5858.jpg
Error: File not found: query_images/Image_1689.jpg
Error: File not found: query_images/Image_5640.jpg
Error: File not found: query_images/Image_2260.jpg
Error: File not found: query_images/Image_638.jpg
Error: File not found: query_images/Image_5671.jpg
Error: File not found: query_images/Image_10022.jpg
Error: File not found: query_images/Image_11359.jpg
Error: File not found: query_images/Image_8462.jpg
Error: File not found: query_images/Image_3618.jpg
Error: File not found: query_images/Image_12169.jpg
Error: File not found: query_images/Image_5321.jpg
Error: File not found: query_images/Image_8875.jpg
Error: File not found: query_images/Image_1263.jpg
Error: File not found: query_images/Image_1913.jpg
Error: File not found: query_

Computing query embeddings:  50%|█████▍     | 574/1150 [00:03<00:02, 206.05it/s]

Error: File not found: query_images/Image_9086.jpg
Error: File not found: query_images/Image_11650.jpg
Error: File not found: query_images/Image_11258.jpg
Error: File not found: query_images/Image_1229.jpg
Error: File not found: query_images/Image_3957.jpg
Error: File not found: query_images/Image_3612.jpg
Error: File not found: query_images/Image_4452.jpg
Error: File not found: query_images/Image_7163.jpg
Error: File not found: query_images/Image_6228.jpg
Error: File not found: query_images/Image_10883.jpg
Error: File not found: query_images/Image_9605.jpg
Error: File not found: query_images/Image_8746.jpg
Error: File not found: query_images/Image_3604.jpg
Error: File not found: query_images/Image_2163.jpg
Error: File not found: query_images/Image_1851.jpg
Error: File not found: query_images/Image_11118.jpg
Error: File not found: query_images/Image_12483.jpg
Error: File not found: query_images/Image_4646.jpg
Error: File not found: query_images/Image_9493.jpg
Error: File not found: que

Computing query embeddings:  52%|█████▋     | 595/1150 [00:03<00:03, 182.35it/s]

Error: File not found: query_images/Image_2907.jpg
Error: File not found: query_images/Image_3194.jpg
Error: File not found: query_images/Image_12264.jpg
Error: File not found: query_images/Image_4749.jpg
Error: File not found: query_images/Image_1566.jpg
Error: File not found: query_images/Image_6834.jpg
Error: File not found: query_images/Image_2931.jpg


Computing query embeddings:  53%|█████▊     | 614/1150 [00:03<00:03, 160.59it/s]

Error: File not found: query_images/Image_11355.jpg
Error: File not found: query_images/Image_10794.jpg
Error: File not found: query_images/Image_7802.jpg
Error: File not found: query_images/Image_11606.jpg
Error: File not found: query_images/Image_1765.jpg
Error: File not found: query_images/Image_5348.jpg
Error: File not found: query_images/Image_8536.jpg
Error: File not found: query_images/Image_10420.jpg
Error: File not found: query_images/Image_5200.jpg
Error: File not found: query_images/Image_2396.jpg
Error: File not found: query_images/Image_1166.jpg
Error: File not found: query_images/Image_1636.jpg
Error: File not found: query_images/Image_7593.jpg
Error: File not found: query_images/Image_6726.jpg
Error: File not found: query_images/Image_7946.jpg
Error: File not found: query_images/Image_5603.jpg
Error: File not found: query_images/Image_648.jpg
Error: File not found: query_images/Image_3129.jpg
Error: File not found: query_images/Image_10028.jpg
Error: File not found: quer

Computing query embeddings:  56%|██████▏    | 647/1150 [00:03<00:03, 150.65it/s]

Error: File not found: query_images/Image_12156.jpg
Error: File not found: query_images/Image_6975.jpg
Error: File not found: query_images/Image_1781.jpg
Error: File not found: query_images/Image_1249.jpg
Error: File not found: query_images/Image_4512.jpg
Error: File not found: query_images/Image_1578.jpg
Error: File not found: query_images/Image_10873.jpg
Error: File not found: query_images/Image_5828.jpg
Error: File not found: query_images/Image_9423.jpg
Error: File not found: query_images/Image_10816.jpg
Error: File not found: query_images/Image_7869.jpg
Error: File not found: query_images/Image_6444.jpg
Error: File not found: query_images/Image_7019.jpg
Error: File not found: query_images/Image_2736.jpg
Error: File not found: query_images/Image_2976.jpg
Error: File not found: query_images/Image_8673.jpg
Error: File not found: query_images/Image_158.jpg
Error: File not found: query_images/Image_366.jpg
Error: File not found: query_images/Image_6799.jpg
Error: File not found: query_i

Computing query embeddings:  58%|██████▎    | 663/1150 [00:03<00:03, 149.61it/s]

Error: File not found: query_images/Image_9953.jpg
Error: File not found: query_images/Image_10114.jpg
Error: File not found: query_images/Image_4113.jpg
Error: File not found: query_images/Image_4325.jpg
Error: File not found: query_images/Image_4510.jpg
Error: File not found: query_images/Image_10570.jpg
Error: File not found: query_images/Image_4390.jpg
Error: File not found: query_images/Image_11746.jpg
Error: File not found: query_images/Image_1452.jpg
Error: File not found: query_images/Image_9822.jpg
Error: File not found: query_images/Image_5839.jpg
Error: File not found: query_images/Image_11930.jpg
Error: File not found: query_images/Image_7135.jpg
Error: File not found: query_images/Image_4986.jpg
Error: File not found: query_images/Image_9890.jpg
Error: File not found: query_images/Image_7065.jpg
Error: File not found: query_images/Image_6853.jpg
Error: File not found: query_images/Image_10855.jpg
Error: File not found: query_images/Image_4553.jpg
Error: File not found: que

Computing query embeddings:  59%|██████▍    | 679/1150 [00:03<00:03, 141.70it/s]

Error: File not found: query_images/Image_12402.jpg
Error: File not found: query_images/Image_6262.jpg
Error: File not found: query_images/Image_5666.jpg
Error: File not found: query_images/Image_423.jpg
Error: File not found: query_images/Image_3256.jpg


Computing query embeddings:  60%|██████▋    | 694/1150 [00:04<00:03, 135.46it/s]

Error: File not found: query_images/Image_5481.jpg
Error: File not found: query_images/Image_6383.jpg
Error: File not found: query_images/Image_1150.jpg
Error: File not found: query_images/Image_4117.jpg
Error: File not found: query_images/Image_11986.jpg
Error: File not found: query_images/Image_6901.jpg
Error: File not found: query_images/Image_9211.jpg
Error: File not found: query_images/Image_2997.jpg
Error: File not found: query_images/Image_7521.jpg
Error: File not found: query_images/Image_985.jpg
Error: File not found: query_images/Image_8968.jpg
Error: File not found: query_images/Image_11364.jpg
Error: File not found: query_images/Image_8535.jpg
Error: File not found: query_images/Image_12043.jpg
Error: File not found: query_images/Image_5080.jpg
Error: File not found: query_images/Image_386.jpg
Error: File not found: query_images/Image_6926.jpg
Error: File not found: query_images/Image_6034.jpg
Error: File not found: query_images/Image_2560.jpg
Error: File not found: query_i

Computing query embeddings:  63%|██████▉    | 723/1150 [00:04<00:03, 137.95it/s]

Error: File not found: query_images/Image_10567.jpg
Error: File not found: query_images/Image_265.jpg
Error: File not found: query_images/Image_3040.jpg
Error: File not found: query_images/Image_636.jpg
Error: File not found: query_images/Image_5242.jpg
Error: File not found: query_images/Image_7995.jpg
Error: File not found: query_images/Image_6967.jpg
Error: File not found: query_images/Image_10714.jpg
Error: File not found: query_images/Image_1089.jpg
Error: File not found: query_images/Image_2299.jpg
Error: File not found: query_images/Image_8263.jpg
Error: File not found: query_images/Image_4404.jpg
Error: File not found: query_images/Image_11211.jpg
Error: File not found: query_images/Image_10550.jpg
Error: File not found: query_images/Image_3765.jpg
Error: File not found: query_images/Image_10031.jpg
Error: File not found: query_images/Image_12493.jpg
Error: File not found: query_images/Image_2224.jpg
Error: File not found: query_images/Image_10796.jpg
Error: File not found: que

Computing query embeddings:  64%|███████    | 737/1150 [00:04<00:02, 138.12it/s]

Error: File not found: query_images/Image_837.jpg
Error: File not found: query_images/Image_11457.jpg
Error: File not found: query_images/Image_9411.jpg
Error: File not found: query_images/Image_10968.jpg
Error: File not found: query_images/Image_3234.jpg


Computing query embeddings:  65%|███████▏   | 752/1150 [00:04<00:02, 140.55it/s]

Error: File not found: query_images/Image_11304.jpg
Error: File not found: query_images/Image_1202.jpg
Error: File not found: query_images/Image_4898.jpg
Error: File not found: query_images/Image_501.jpg
Error: File not found: query_images/Image_9941.jpg
Error: File not found: query_images/Image_5256.jpg
Error: File not found: query_images/Image_9552.jpg
Error: File not found: query_images/Image_1795.jpg
Error: File not found: query_images/Image_9732.jpg
Error: File not found: query_images/Image_2393.jpg
Error: File not found: query_images/Image_3665.jpg
Error: File not found: query_images/Image_11829.jpg
Error: File not found: query_images/Image_350.jpg
Error: File not found: query_images/Image_5414.jpg
Error: File not found: query_images/Image_3509.jpg
Error: File not found: query_images/Image_6733.jpg
Error: File not found: query_images/Image_4611.jpg
Error: File not found: query_images/Image_10364.jpg
Error: File not found: query_images/Image_2993.jpg
Error: File not found: query_i

Computing query embeddings:  69%|███████▌   | 790/1150 [00:04<00:02, 162.11it/s]

Error: File not found: query_images/Image_12391.jpg
Error: File not found: query_images/Image_11727.jpg
Error: File not found: query_images/Image_9358.jpg
Error: File not found: query_images/Image_2341.jpg
Error: File not found: query_images/Image_3651.jpg
Error: File not found: query_images/Image_9898.jpg
Error: File not found: query_images/Image_10186.jpg
Error: File not found: query_images/Image_6722.jpg
Error: File not found: query_images/Image_3628.jpg
Error: File not found: query_images/Image_7795.jpg
Error: File not found: query_images/Image_3696.jpg
Error: File not found: query_images/Image_5158.jpg
Error: File not found: query_images/Image_7779.jpg
Error: File not found: query_images/Image_1176.jpg
Error: File not found: query_images/Image_7920.jpg
Error: File not found: query_images/Image_6822.jpg
Error: File not found: query_images/Image_8811.jpg
Error: File not found: query_images/Image_6072.jpg
Error: File not found: query_images/Image_2128.jpg
Error: File not found: query

Computing query embeddings:  72%|███████▉   | 826/1150 [00:04<00:01, 167.60it/s]

Error: File not found: query_images/Image_2743.jpg
Error: File not found: query_images/Image_10621.jpg
Error: File not found: query_images/Image_10450.jpg
Error: File not found: query_images/Image_7729.jpg
Error: File not found: query_images/Image_3137.jpg
Error: File not found: query_images/Image_2371.jpg
Error: File not found: query_images/Image_185.jpg
Error: File not found: query_images/Image_4770.jpg
Error: File not found: query_images/Image_1732.jpg
Error: File not found: query_images/Image_7258.jpg
Error: File not found: query_images/Image_8561.jpg
Error: File not found: query_images/Image_1524.jpg
Error: File not found: query_images/Image_12165.jpg
Error: File not found: query_images/Image_191.jpg
Error: File not found: query_images/Image_12092.jpg
Error: File not found: query_images/Image_9723.jpg
Error: File not found: query_images/Image_10121.jpg
Error: File not found: query_images/Image_937.jpg
Error: File not found: query_images/Image_12403.jpg
Error: File not found: query

Computing query embeddings:  75%|████████▏  | 861/1150 [00:05<00:01, 167.87it/s]

Error: File not found: query_images/Image_2990.jpg
Error: File not found: query_images/Image_2259.jpg
Error: File not found: query_images/Image_539.jpg
Error: File not found: query_images/Image_11673.jpg
Error: File not found: query_images/Image_10407.jpg
Error: File not found: query_images/Image_2003.jpg
Error: File not found: query_images/Image_6064.jpg
Error: File not found: query_images/Image_11202.jpg
Error: File not found: query_images/Image_8174.jpg
Error: File not found: query_images/Image_9751.jpg
Error: File not found: query_images/Image_4342.jpg
Error: File not found: query_images/Image_982.jpg
Error: File not found: query_images/Image_275.jpg
Error: File not found: query_images/Image_4906.jpg
Error: File not found: query_images/Image_5741.jpg
Error: File not found: query_images/Image_2162.jpg
Error: File not found: query_images/Image_10635.jpg
Error: File not found: query_images/Image_6023.jpg
Error: File not found: query_images/Image_6299.jpg
Error: File not found: query_i

Computing query embeddings:  78%|████████▌  | 899/1150 [00:05<00:01, 172.75it/s]

Error: File not found: query_images/Image_8096.jpg
Error: File not found: query_images/Image_10375.jpg
Error: File not found: query_images/Image_10058.jpg
Error: File not found: query_images/Image_7033.jpg
Error: File not found: query_images/Image_9505.jpg
Error: File not found: query_images/Image_4952.jpg
Error: File not found: query_images/Image_9925.jpg
Error: File not found: query_images/Image_4415.jpg
Error: File not found: query_images/Image_8563.jpg
Error: File not found: query_images/Image_8708.jpg
Error: File not found: query_images/Image_12234.jpg
Error: File not found: query_images/Image_8692.jpg
Error: File not found: query_images/Image_7358.jpg
Error: File not found: query_images/Image_8130.jpg
Error: File not found: query_images/Image_2643.jpg
Error: File not found: query_images/Image_2798.jpg
Error: File not found: query_images/Image_5375.jpg
Error: File not found: query_images/Image_2214.jpg
Error: File not found: query_images/Image_3159.jpg
Error: File not found: query

Computing query embeddings:  81%|████████▉  | 935/1150 [00:05<00:01, 175.52it/s]

Error: File not found: query_images/Image_6423.jpg
Error: File not found: query_images/Image_5128.jpg
Error: File not found: query_images/Image_8106.jpg
Error: File not found: query_images/Image_10269.jpg
Error: File not found: query_images/Image_10117.jpg
Error: File not found: query_images/Image_3205.jpg
Error: File not found: query_images/Image_620.jpg
Error: File not found: query_images/Image_8422.jpg
Error: File not found: query_images/Image_11033.jpg
Error: File not found: query_images/Image_3778.jpg
Error: File not found: query_images/Image_1843.jpg
Error: File not found: query_images/Image_10542.jpg
Error: File not found: query_images/Image_8228.jpg
Error: File not found: query_images/Image_6198.jpg
Error: File not found: query_images/Image_7606.jpg
Error: File not found: query_images/Image_9071.jpg
Error: File not found: query_images/Image_266.jpg
Error: File not found: query_images/Image_11847.jpg
Error: File not found: query_images/Image_1834.jpg
Error: File not found: query

Computing query embeddings:  85%|█████████▎ | 972/1150 [00:05<00:01, 173.50it/s]

Error: File not found: query_images/Image_5490.jpg
Error: File not found: query_images/Image_676.jpg
Error: File not found: query_images/Image_9441.jpg
Error: File not found: query_images/Image_6370.jpg
Error: File not found: query_images/Image_5814.jpg
Error: File not found: query_images/Image_4546.jpg
Error: File not found: query_images/Image_4378.jpg
Error: File not found: query_images/Image_6443.jpg
Error: File not found: query_images/Image_4193.jpg
Error: File not found: query_images/Image_5770.jpg
Error: File not found: query_images/Image_322.jpg
Error: File not found: query_images/Image_9881.jpg
Error: File not found: query_images/Image_3686.jpg
Error: File not found: query_images/Image_981.jpg
Error: File not found: query_images/Image_6059.jpg
Error: File not found: query_images/Image_4602.jpg
Error: File not found: query_images/Image_10477.jpg
Error: File not found: query_images/Image_4940.jpg
Error: File not found: query_images/Image_7782.jpg
Error: File not found: query_imag

Computing query embeddings:  88%|████████▊ | 1008/1150 [00:05<00:00, 161.22it/s]

Error: File not found: query_images/Image_12125.jpg
Error: File not found: query_images/Image_6658.jpg
Error: File not found: query_images/Image_12455.jpg
Error: File not found: query_images/Image_9016.jpg
Error: File not found: query_images/Image_12294.jpg
Error: File not found: query_images/Image_372.jpg
Error: File not found: query_images/Image_7930.jpg
Error: File not found: query_images/Image_6585.jpg
Error: File not found: query_images/Image_617.jpg
Error: File not found: query_images/Image_7699.jpg
Error: File not found: query_images/Image_10975.jpg
Error: File not found: query_images/Image_6567.jpg
Error: File not found: query_images/Image_10672.jpg
Error: File not found: query_images/Image_3161.jpg
Error: File not found: query_images/Image_11400.jpg


Computing gallery embeddings:  89%|███████ | 1018/1150 [00:09<00:00, 134.37it/s]

Error: File not found: gallery/Image_3280.jpg
Error: File not found: gallery/Image_10750.jpg
Error: File not found: gallery/Image_1708.jpg
Error: File not found: gallery/Image_11520.jpg
Error: File not found: gallery/Image_6878.jpg
Error: File not found: gallery/Image_7368.jpg
Error: File not found: gallery/Image_4502.jpg
Error: File not found: gallery/Image_2794.jpg
Error: File not found: gallery/Image_3174.jpg
Error: File not found: gallery/Image_4138.jpg
Error: File not found: gallery/Image_7134.jpg
Error: File not found: gallery/Image_3421.jpg
Error: File not found: gallery/Image_11736.jpg
Error: File not found: gallery/Image_12115.jpg
Error: File not found: gallery/Image_9431.jpg
Error: File not found: gallery/Image_9139.jpg
Error: File not found: gallery/Image_3806.jpg
Error: File not found: gallery/Image_4175.jpg
Error: File not found: gallery/Image_10913.jpg
Error: File not found: gallery/Image_11290.jpg
Error: File not found: gallery/Image_11916.jpg
Error: File not found: gall

Computing gallery embeddings:  91%|███████▎| 1051/1150 [00:09<00:00, 144.73it/s]

Error: File not found: gallery/Image_7316.jpg
Error: File not found: gallery/Image_608.jpg
Error: File not found: gallery/Image_5850.jpg
Error: File not found: gallery/Image_7430.jpg
Error: File not found: gallery/Image_8346.jpg
Error: File not found: gallery/Image_3416.jpg
Error: File not found: gallery/Image_6656.jpg
Error: File not found: gallery/Image_9409.jpg
Error: File not found: gallery/Image_7735.jpg
Error: File not found: gallery/Image_10700.jpg
Error: File not found: gallery/Image_3704.jpg
Error: File not found: gallery/Image_11323.jpg
Error: File not found: gallery/Image_3103.jpg
Error: File not found: gallery/Image_2024.jpg
Error: File not found: gallery/Image_8473.jpg
Error: File not found: gallery/Image_7310.jpg
Error: File not found: gallery/Image_9165.jpg
Error: File not found: gallery/Image_9121.jpg
Error: File not found: gallery/Image_1701.jpg
Error: File not found: gallery/Image_3893.jpg
Error: File not found: gallery/Image_10639.jpg
Error: File not found: gallery/I

Computing gallery embeddings:  95%|███████▌| 1089/1150 [00:09<00:00, 161.65it/s]

Error: File not found: gallery/Image_1052.jpg
Error: File not found: gallery/Image_3076.jpg
Error: File not found: gallery/Image_7719.jpg
Error: File not found: gallery/Image_507.jpg
Error: File not found: gallery/Image_2877.jpg
Error: File not found: gallery/Image_959.jpg
Error: File not found: gallery/Image_1668.jpg
Error: File not found: gallery/Image_12213.jpg
Error: File not found: gallery/Image_7100.jpg
Error: File not found: gallery/Image_4855.jpg
Error: File not found: gallery/Image_10945.jpg
Error: File not found: gallery/Image_10340.jpg
Error: File not found: gallery/Image_10245.jpg
Error: File not found: gallery/Image_11414.jpg
Error: File not found: gallery/Image_11549.jpg
Error: File not found: gallery/Image_516.jpg
Error: File not found: gallery/Image_1327.jpg
Error: File not found: gallery/Image_8385.jpg
Error: File not found: gallery/Image_495.jpg
Error: File not found: gallery/Image_2624.jpg
Error: File not found: gallery/Image_498.jpg
Error: File not found: gallery/Im

Computing gallery embeddings:  98%|███████▊| 1126/1150 [00:09<00:00, 168.58it/s]

Error: File not found: gallery/Image_6551.jpg
Error: File not found: gallery/Image_3613.jpg
Error: File not found: gallery/Image_4379.jpg
Error: File not found: gallery/Image_3437.jpg
Error: File not found: gallery/Image_7923.jpg
Error: File not found: gallery/Image_10587.jpg
Error: File not found: gallery/Image_10454.jpg
Error: File not found: gallery/Image_6714.jpg
Error: File not found: gallery/Image_4680.jpg
Error: File not found: gallery/Image_5258.jpg
Error: File not found: gallery/Image_3959.jpg
Error: File not found: gallery/Image_8572.jpg
Error: File not found: gallery/Image_12539.jpg
Error: File not found: gallery/Image_4759.jpg
Error: File not found: gallery/Image_11300.jpg
Error: File not found: gallery/Image_5632.jpg
Error: File not found: gallery/Image_12454.jpg
Error: File not found: gallery/Image_7338.jpg
Error: File not found: gallery/Image_9694.jpg
Error: File not found: gallery/Image_8608.jpg
Error: File not found: gallery/Image_7461.jpg
Error: File not found: galler

Computing gallery embeddings: 100%|████████| 1150/1150 [00:09<00:00, 116.03it/s]

Error: File not found: gallery/Image_10017.jpg
Error: File not found: gallery/Image_6115.jpg
Error: File not found: gallery/Image_852.jpg
Error: File not found: gallery/Image_2049.jpg
Error: File not found: gallery/Image_10457.jpg
Error: File not found: gallery/Image_1344.jpg
Error: File not found: gallery/Image_12295.jpg
Error: File not found: gallery/Image_3880.jpg
Error: File not found: gallery/Image_9129.jpg
Error: File not found: gallery/Image_1130.jpg
Error: File not found: gallery/Image_3897.jpg


In [12]:
# Compute similarity scores and rank the gallery images
ranks = []
for query_embedding in tqdm(query_embeddings, desc='Ranking gallery images'):
    similarities = torch.mm(gallery_embeddings, query_embedding.unsqueeze(1)).squeeze()
    sorted_indices = torch.argsort(similarities, descending=True)
    ranks.append(sorted_indices)

Ranking gallery images: 100%|████████████| 1150/1150 [00:00<00:00, 16256.72it/s]


In [16]:
ranks

[tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1149]),
 tensor([   0,    1,    2,  ..., 1147, 1148, 1

In [13]:
# Compute evaluation metrics
mAP_1 = 0.0
mAP_10 = 0.0
mAP_50 = 0.0
mean_rank = 0.0

for i, rank in enumerate(ranks):
    query_label = query_dataset.labels[i]
    gallery_labels = [gallery_dataset.labels[idx.item()] for idx in rank]

    # Compute mAP@1
    if gallery_labels[0] == query_label:
        mAP_1 += 1.0

    # Compute mAP@10
    precision_at_10 = sum(1 for label in gallery_labels[:10] if label == query_label) / 10
    mAP_10 += precision_at_10

    # Compute mAP@50
    precision_at_50 = sum(1 for label in gallery_labels[:50] if label == query_label) / 50
    mAP_50 += precision_at_50

    # Compute mean rank
    rank_of_first_match = next((i for i, label in enumerate(gallery_labels) if label == query_label), len(gallery_labels))
    mean_rank += rank_of_first_match

      
mAP_1 /= len(ranks)
mAP_10 /= len(ranks)
mAP_50 /= len(ranks)
mean_rank /= len(ranks)

print(f'mAP@1: {mAP_1}')
print(f'mAP@10: {mAP_10}')
print(f'mAP@50: {mAP_50}')
print(f'Mean Rank: {mean_rank}')

mAP@1: 0.06695652173913043
mAP@10: 0.06695652173913043
mAP@50: 0.06695652173913043
Mean Rank: 466.88260869565215
